package com.stu.multithreading.mapper;

import com.stu.multithreading.entity.Msg;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int insert(Msg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    Msg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    List<Msg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int updateByPrimaryKey(Msg row);
}