package com.stu.multithreading.mapper;

import com.stu.multithreading.entity.Trace;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int insert(Trace row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    Trace selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    List<Trace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    int updateByPrimaryKey(Trace row);
}