package com.stu.multithreading.entity;

import java.util.Date;

public class Msg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.name
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.status
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.create_time
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Msg(Long id, String name, Integer status, Date createTime, String msg) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.createTime = createTime;
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Msg() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.id
     *
     * @return the value of msg.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.id
     *
     * @param id the value for msg.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.name
     *
     * @return the value of msg.name
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.name
     *
     * @param name the value for msg.name
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.status
     *
     * @return the value of msg.status
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.status
     *
     * @param status the value for msg.status
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.create_time
     *
     * @return the value of msg.create_time
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.create_time
     *
     * @param createTime the value for msg.create_time
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.msg
     *
     * @return the value of msg.msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.msg
     *
     * @param msg the value for msg.msg
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}