package com.stu.multithreading.entity;

public class Trace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trace.msg_id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    private Long msgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Trace(Long id, Long msgId) {
        this.id = id;
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Trace() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace.id
     *
     * @return the value of trace.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace.id
     *
     * @param id the value for trace.id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trace.msg_id
     *
     * @return the value of trace.msg_id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trace.msg_id
     *
     * @param msgId the value for trace.msg_id
     *
     * @mbg.generated Sun Mar 05 20:34:04 CST 2023
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }
}